export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
export const SEARCH_REQUESTED = 'SEARCH_REQUESTED';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILED = 'SEARCH_FAILED';
